[package]
name = "vesper-update"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vesper-core.workspace = true
reqwest.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true

[dev-dependencies]
tokio-test = "0.4"