[package]
name = "vesper-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vesper-ui"
path = "src/main.rs"

[dependencies]
vesper-core.workspace = true
vesper-proto.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
eframe.workspace = true
egui.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true